AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: verify emails and get emails from domains
Resources:
  yeagerskill:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: verify emails and get emails from domains
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::973880726729:role/lambda_basic_execution'
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
